[package]
name = "rodio"
version = "0.4.2"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "Apache-2.0"
description = "Audio playback library"
keywords = ["audio", "playback", "gamedev"]
repository = "https://github.com/tomaka/rodio"
documentation = "http://docs.rs/rodio"

[dependencies]
claxon = "0.3.0"
cpal = "0.4.0"
futures = "0.1.1"
hound = "1.0.0"
lazy_static = "0.1.12"
lewton = "0.5"
simplemad = "0.8.1"
simplemad_sys = "0.5.0"
